### ISSUE TITLE
Kubesec should generate valid secrets with the cleartext flag

### ISSUE THREAD

**Issue by wmedlar** [shyiko/kubesec#11]
Sometime around 1.6, I believe, the `.stringData` field was added to the [Secret spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#secret-v1-core), allowing non-b64-encoded data to be supplied to the apiserver. This is quite handy for managing updates with secrets without having to go through the whole decoding/encoding cycle.

Kubeseal already supports decoding base64 secrets, but outputs the raw strings to `.data`, which makes for invalid secrets; outputting that to `.stringData` would retain validity.

**Comment by shyiko** [comment]
Hi, Will.

I've just released [0.9.0](https://github.com/shyiko/kubesec/blob/master/CHANGELOG.md#090---2018-06-25) which has `stringData` support. 

Basically, everywhere you would normally use `--data`/`-d` to set the `data` (e.g. with `kubesec create`, `kubesec patch`, etc) you can now use `--string-data/-s` to set `stringData`. 

I can't change the behavior of `--cleartext`/`-x` as that would be a breaking change, but hopefully, with `stringData` support in place, you'll no longer need it.

Let me know if you have any concerns. I'm always open to suggestions.

**Comment by wmedlar** [comment]
Wow, thanks for the rapid turnaround on this!
