### ISSUE TITLE
`gpg` wasn't found (make sure it's available on the PATH)

### ISSUE THREAD

**Issue by valentin2105** [shyiko/kubesec#2]
Hi,

I'm trying kubesec on my Macbook, and I got this error : 

```
`gpg` wasn't found (make sure it's available on the PATH)
```

But, it's strange, because `gpg` command work fine : 

```
15:05:18 › which gpg
/usr/local/bin/gpg

15:05:20 › gpg
gpg: Go ahead and type your message ...
^C
gpg: Interrupt caught ... exiting
```

Thanks a lot, this tool look awesome.

**Comment by shyiko** [comment]
@valentin2105 Thank you for the issue. Fixed in [0.1.1](https://github.com/shyiko/kubesec/blob/master/CHANGELOG.md#011---2017-08-15). :balloon:
