### ISSUE TITLE
include license file in source code

### ISSUE THREAD

**Issue by mfinelli** [shyiko/kubesec#8]
Could you please include a copy of the MIT license along with the source code for this project? It would make the lives of people packaging and distributing it much easier.

**Comment by tamalsaha** [comment]
I would request to consider Apache 2 license https://www.cncf.io/blog/2017/02/01/cncf-recommends-aslv2/

**Comment by shyiko** [comment]
Interesting. Thank you for the link, @tamalsaha. I'm OK with whichever license is safest for the contributors. If it happens to be Apache-2.0 - so be it.

**Comment by shyiko** [comment]
[kubesec@0.8.0](https://github.com/shyiko/kubesec/blob/master/CHANGELOG.md#080---2018-05-06) (https://github.com/shyiko/kubesec/commit/e6d96c4b31ab401e796c9e113475bf41d6568f92) released.
